//user
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//credit card accounts
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const GET_ACCOUNTS_BILL = "GET_ACCOUNTS";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";


//offline account
export const ADD_OFFLINE_ACCOUNT = "ADD_OFFLINE_ACCOUNT";
export const DELETE_OFFLINE_ACCOUNT = "DELETE_OFFLINE_ACCOUNT";
export const GET_OFFLINE_ACCOUNTS = "GET_OFFLINE_ACCOUNTS";
export const ACCOUNTS_OFFLINE_LOADING = "ACCOUNTS_OFFLINE_LOADING";
export const ACCOUNTS_OFFLINE_BILL = "ACCOUNTS_OFFLINE_BILL";

//reminder onlineaccount
export const ADD_REMINDER_ONLINE = "ADD_REMINDER_ONLINE";
export const DELETE_REMINDER_ONLINE = "DELETE_REMINDER_ONLINE";


//reminder offlineaccount
export const ADD_REMINDER_OFFLINE = "ADD_REMINDER_OFFLINE";
export const DELETE_REMINDER_OFFLINE = "DELETE_REMINDER_OFFLINE";


